networks:
  opsci-net:
    driver: bridge

volumes:
  postgres_data:

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strapi
    env_file:
      - .env
    depends_on:
      - postgres-container
      - kafka
    ports:
      - "1337:1337"
    networks:
      - opsci-net
    volumes:
      - ./dgu_mchen:/opt/app/src/api
    restart: unless-stopped

  postgres-container:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dgumchen
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - opsci-net
    restart: unless-stopped

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - opsci-net
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    networks:
      - opsci-net
    restart: unless-stopped
  event-producer:
    build:
      context: ./event-producer
    container_name: event-producer
    env_file:
      - .env
    environment:
      BROKER_1: kafka:9092
      BROKER_2: kafka:9092
      BROKER_3: kafka:9092
      TOPIC: event
      ERROR_TOPIC: errors
    depends_on:
      - kafka
    networks:
      - opsci-net
    restart: unless-stopped

  event-consumer:
    build:
      context: ./event-consumer
    container_name: event-consumer
    env_file:
      - .env
    environment:
      BROKER_1: kafka:9092
      BROKER_2: kafka:9092
      BROKER_3: kafka:9092
      STRAPI_URL: http://strapi:1337
      STRAPI_TOKEN: 9ad94210b50feb682424894b42671a880bad527c16daf6c1781e7f00c02f7d60d16b0e47ea5ebfa93b1f8bb6017ab838aed0f06edcbd0c25c747b3844f9d5a11f8c6a35140b06cbab0392993f2e2c86df95d57f17f39fd0b7caf0498d9b7c0d9b582d225adab6b0b7e3dc949c00734321e5a60dadbe7a3a111b8434bd0830876
      TOPIC: event
      BEGINNING: "false"
      ERROR_TOPIC: errors
    depends_on:
      - kafka
      - strapi
    networks:
      - opsci-net
    restart: unless-stopped

  product-producer:
    build:
      context: ./product-producer
    container_name: product-producer
    env_file:
      - .env
    environment:
      BROKER_1: kafka:9092
      BROKER_2: kafka:9092
      BROKER_3: kafka:9092
      TOPIC: product
      ERROR_TOPIC: errors
    depends_on:
      - kafka
    networks:
      - opsci-net
    restart: unless-stopped

  product-consumer:
    build:
      context: ./product-consumer
    container_name: product-consumer
    env_file:
      - .env
    environment:
      BROKER_1: kafka:9092
      BROKER_2: kafka:9092
      BROKER_3: kafka:9092
      STRAPI_URL: http://strapi:1337
      STRAPI_TOKEN: 9ad94210b50feb682424894b42671a880bad527c16daf6c1781e7f00c02f7d60d16b0e47ea5ebfa93b1f8bb6017ab838aed0f06edcbd0c25c747b3844f9d5a11f8c6a35140b06cbab0392993f2e2c86df95d57f17f39fd0b7caf0498d9b7c0d9b582d225adab6b0b7e3dc949c00734321e5a60dadbe7a3a111b8434bd0830876
      TOPIC: product
      BEGINNING: "false"
      ERROR_TOPIC: errors
    depends_on:
      - kafka
      - strapi
    networks:
      - opsci-net
    restart: unless-stopped

  stock-producer:
    build:
      context: ./stock-producer
    container_name: stock-producer
    env_file:
      - .env
    environment:
      BROKER_1: kafka:9092
      BROKER_2: kafka:9092
      BROKER_3: kafka:9092
      TOPIC: stock
      ERROR_TOPIC: errors
    depends_on:
      - kafka
    networks:
      - opsci-net
    restart: unless-stopped

  stock-consumer:
    build:
      context: ./stock-consumer
    container_name: stock-consumer
    env_file:
      - .env
    environment:
      BROKER_1: kafka:9092
      BROKER_2: kafka:9092
      BROKER_3: kafka:9092
      STRAPI_URL: http://strapi:1337
      STRAPI_TOKEN: 9ad94210b50feb682424894b42671a880bad527c16daf6c1781e7f00c02f7d60d16b0e47ea5ebfa93b1f8bb6017ab838aed0f06edcbd0c25c747b3844f9d5a11f8c6a35140b06cbab0392993f2e2c86df95d57f17f39fd0b7caf0498d9b7c0d9b582d225adab6b0b7e3dc949c00734321e5a60dadbe7a3a111b8434bd0830876
      TOPIC: stock
      BEGINNING: "false"
      ERROR_TOPIC: errors
    depends_on:
      - kafka
      - strapi
    networks:
      - opsci-net
    restart: unless-stopped

